### ISSUE TITLE
kairos-cli: deposit integration

### ISSUE THREAD

**Issue by marijanp** [cspr-rad/kairos#92]
The following PR's implement the kairos-cli deposit integration. The PR's can be reviewed in any order but merged in the following order:

- [x] 1. #89 is needed for the kairos-test-utils to achieve a more congruent configuration with the actual CLI binary. All of the logic is now in `kairos_server::run`
- [x] 2. #90 then uses the `kairos_server::run` instead of the binary-cli to solve a chicken and egg-problem.
- [x] 3. #91 implements the integration with the `kairos-server`. `kairos-test-utils` is then used in an integration test to verify that submitting to the kairos-server works
- [x] 4. #94 submit the deposit deploy to L1
- [ ] 5. update end-to-end to await deposit deploy, after it was submitted through the CLI 
  - [x] 5.1 **NEEDS_REVIEW**:   #110
  - [ ] 5.2 **NEXT**: create a mock data availability layer, circumvent the batch submission and verification, and query whether the deposit was added correctly
